-- StoryScroll Database Schema for PostgreSQL
-- This schema is automatically generated by Django migrations
-- Run: python manage.py makemigrations && python manage.py migrate

-- Note: Django ORM handles table creation automatically.
-- This SQL file is provided for reference only.

-- Users Table (extends Django's auth_user)
-- Django creates: auth_user table with additional fields from User model
CREATE TABLE IF NOT EXISTS blog_user (
    id SERIAL PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMP,
    is_superuser BOOLEAN NOT NULL,
    username VARCHAR(150) UNIQUE NOT NULL,
    first_name VARCHAR(150),
    last_name VARCHAR(150),
    email VARCHAR(254),
    is_staff BOOLEAN NOT NULL,
    is_active BOOLEAN NOT NULL,
    date_joined TIMESTAMP NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'Reader' CHECK (role IN ('Admin', 'Writer', 'Reader')),
    bio TEXT,
    profile_pic VARCHAR(100)
);

-- Posts Table
CREATE TABLE IF NOT EXISTS blog_post (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    author_id INTEGER NOT NULL REFERENCES blog_user(id) ON DELETE CASCADE,
    category VARCHAR(20) NOT NULL DEFAULT 'Other' CHECK (category IN (
        'Technology', 'Lifestyle', 'Travel', 'Food', 'Fashion', 
        'Health', 'Education', 'Business', 'Entertainment', 'Other'
    )),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    featured_image VARCHAR(100)
);

-- Comments Table (with support for replies via parent_id)
CREATE TABLE IF NOT EXISTS blog_comment (
    id SERIAL PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES blog_user(id) ON DELETE CASCADE,
    parent_id INTEGER REFERENCES blog_comment(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Likes Table (unique constraint prevents duplicate likes)
CREATE TABLE IF NOT EXISTS blog_like (
    id SERIAL PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES blog_post(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES blog_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(post_id, user_id)
);

-- Follows Table (unique constraint prevents duplicate follows)
CREATE TABLE IF NOT EXISTS blog_follow (
    id SERIAL PRIMARY KEY,
    follower_id INTEGER NOT NULL REFERENCES blog_user(id) ON DELETE CASCADE,
    followed_author_id INTEGER NOT NULL REFERENCES blog_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(follower_id, followed_author_id),
    CHECK (follower_id != followed_author_id)
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_post_author ON blog_post(author_id);
CREATE INDEX IF NOT EXISTS idx_post_category ON blog_post(category);
CREATE INDEX IF NOT EXISTS idx_post_created ON blog_post(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comment_post ON blog_comment(post_id);
CREATE INDEX IF NOT EXISTS idx_comment_user ON blog_comment(user_id);
CREATE INDEX IF NOT EXISTS idx_comment_parent ON blog_comment(parent_id);
CREATE INDEX IF NOT EXISTS idx_like_post ON blog_like(post_id);
CREATE INDEX IF NOT EXISTS idx_like_user ON blog_like(user_id);
CREATE INDEX IF NOT EXISTS idx_follow_follower ON blog_follow(follower_id);
CREATE INDEX IF NOT EXISTS idx_follow_followed ON blog_follow(followed_author_id);

-- Query for Author Ranking (by follower count)
-- This query is used in the author_ranking view
SELECT 
    u.id,
    u.username,
    u.email,
    u.bio,
    COUNT(f.id) AS follower_count,
    COUNT(p.id) AS post_count
FROM blog_user u
LEFT JOIN blog_follow f ON u.id = f.followed_author_id
LEFT JOIN blog_post p ON u.id = p.author_id
WHERE u.role = 'Writer'
GROUP BY u.id, u.username, u.email, u.bio
ORDER BY follower_count DESC, u.username ASC;


